#pragma once

#include "macros.h"

TORCHSCIENCE_AUTOGRAD_POINTWISE_UNARY_OPERATOR(gamma, Gamma, z)
TORCHSCIENCE_AUTOGRAD_POINTWISE_UNARY_OPERATOR(digamma, Digamma, z)
TORCHSCIENCE_AUTOGRAD_POINTWISE_UNARY_OPERATOR(trigamma, Trigamma, z)
TORCHSCIENCE_AUTOGRAD_POINTWISE_BINARY_OPERATOR(beta, Beta, a, b)
TORCHSCIENCE_AUTOGRAD_POINTWISE_BINARY_OPERATOR(chebyshev_polynomial_t, ChebyshevPolynomialT, x, n)
TORCHSCIENCE_AUTOGRAD_POINTWISE_TERNARY_OPERATOR(incomplete_beta, IncompleteBeta, x, a, b)
TORCHSCIENCE_AUTOGRAD_POINTWISE_QUATERNARY_OPERATOR(hypergeometric_2_f_1, Hypergeometric2F1, a, b, c, z)
TORCHSCIENCE_AUTOGRAD_POINTWISE_BINARY_OPERATOR(polygamma, Polygamma, n, z)
TORCHSCIENCE_AUTOGRAD_POINTWISE_BINARY_OPERATOR(log_beta, LogBeta, a, b)
TORCHSCIENCE_AUTOGRAD_POINTWISE_UNARY_OPERATOR(log_gamma, LogGamma, z)
TORCHSCIENCE_AUTOGRAD_POINTWISE_BINARY_OPERATOR(regularized_gamma_p, RegularizedGammaP, a, x)
TORCHSCIENCE_AUTOGRAD_POINTWISE_BINARY_OPERATOR(regularized_gamma_q, RegularizedGammaQ, a, x)
TORCHSCIENCE_AUTOGRAD_POINTWISE_UNARY_OPERATOR(modified_bessel_i_0, ModifiedBesselI0, z)
TORCHSCIENCE_AUTOGRAD_POINTWISE_UNARY_OPERATOR(modified_bessel_i_1, ModifiedBesselI1, z)
