"""Differentiable polynomial arithmetic for PyTorch tensors.

This module provides polynomial arithmetic with full autograd support.
Polynomials use ascending coefficient order (NumPy convention) with
batch dimensions first.

Constructors
------------
polynomial
    Create polynomial from coefficients.
polynomial_from_roots
    Construct monic polynomial from its roots.

Arithmetic
----------
polynomial_add
    Add two polynomials.
polynomial_subtract
    Subtract polynomials.
polynomial_multiply
    Multiply polynomials.
polynomial_scale
    Multiply polynomial by scalar.
polynomial_negate
    Negate polynomial.
polynomial_pow
    Raise polynomial to non-negative integer power.

Division
--------
polynomial_divmod
    Divide polynomials, returning quotient and remainder.
polynomial_div
    Quotient of polynomial division.
polynomial_mod
    Remainder of polynomial division.

Composition
-----------
polynomial_compose
    Compute p(q(x)).

Evaluation and Calculus
-----------------------
polynomial_evaluate
    Evaluate polynomial at points.
polynomial_derivative
    Compute derivative.
polynomial_antiderivative
    Compute antiderivative.
polynomial_integral
    Compute definite integral.

Fitting
-------
polynomial_fit
    Fit polynomial to data via least squares.
polynomial_vandermonde
    Construct Vandermonde matrix.

Root Finding
------------
polynomial_roots
    Find roots via companion matrix eigenvalues.

Utilities
---------
polynomial_degree
    Return degree of polynomial.
polynomial_trim
    Remove trailing near-zero coefficients.
polynomial_equal
    Check polynomial equality within tolerance.

Data Types
----------
Polynomial
    Polynomial in power basis with ascending coefficients.

Exceptions
----------
PolynomialError
    Base exception for polynomial operations.
DegreeError
    Invalid degree for operation.

Examples
--------
>>> from torchscience.polynomial._polynomial_evaluate import polynomial_evaluate import torch
>>> from torchscience.polynomial import polynomial

>>> # Create polynomial 1 + 2x + 3x^2
>>> p = polynomial(torch.tensor([1.0, 2.0, 3.0]))

>>> # Evaluate at points
>>> x = torch.tensor([0.0, 1.0, 2.0])
>>> polynomial_evaluate(p, x)
tensor([ 1.,  6., 17.])

>>> # Operator overloading
>>> p(x)  # Same as polynomial_evaluate(p, x)
tensor([ 1.,  6., 17.])

>>> # Division
>>> q = polynomial(torch.tensor([1.0, 1.0]))  # 1 + x
>>> p // q  # Quotient
>>> p % q   # Remainder

>>> # Power
>>> q ** 3  # (1 + x)^3

>>> from torchscience.polynomial._polynomial_fit import polynomial_fit # Fitting
>>> x = torch.tensor([0.0, 1.0, 2.0, 3.0])
>>> y = torch.tensor([1.0, 3.0, 5.0, 7.0])
>>> p = polynomial_fit(x, y, degree=1)  # Fits y = 1 + 2x
"""

from ._chebyshev_polynomial_t import (
    ChebyshevPolynomialT,
    chebyshev_polynomial_t,
    chebyshev_polynomial_t_add,
    chebyshev_polynomial_t_antiderivative,
    chebyshev_polynomial_t_companion,
    chebyshev_polynomial_t_degree,
    chebyshev_polynomial_t_derivative,
    chebyshev_polynomial_t_div,
    chebyshev_polynomial_t_divmod,
    chebyshev_polynomial_t_equal,
    chebyshev_polynomial_t_evaluate,
    chebyshev_polynomial_t_fit,
    chebyshev_polynomial_t_from_roots,
    chebyshev_polynomial_t_integral,
    chebyshev_polynomial_t_interpolate,
    chebyshev_polynomial_t_mod,
    chebyshev_polynomial_t_multiply,
    chebyshev_polynomial_t_mulx,
    chebyshev_polynomial_t_negate,
    chebyshev_polynomial_t_points,
    chebyshev_polynomial_t_pow,
    chebyshev_polynomial_t_roots,
    chebyshev_polynomial_t_scale,
    chebyshev_polynomial_t_subtract,
    chebyshev_polynomial_t_to_polynomial,
    chebyshev_polynomial_t_trim,
    chebyshev_polynomial_t_vandermonde,
    chebyshev_polynomial_t_weight,
    polynomial_to_chebyshev_polynomial_t,
)
from ._chebyshev_polynomial_u import (
    ChebyshevPolynomialU,
    chebyshev_polynomial_u,
    chebyshev_polynomial_u_add,
    chebyshev_polynomial_u_antiderivative,
    chebyshev_polynomial_u_companion,
    chebyshev_polynomial_u_degree,
    chebyshev_polynomial_u_derivative,
    chebyshev_polynomial_u_div,
    chebyshev_polynomial_u_divmod,
    chebyshev_polynomial_u_equal,
    chebyshev_polynomial_u_evaluate,
    chebyshev_polynomial_u_fit,
    chebyshev_polynomial_u_from_roots,
    chebyshev_polynomial_u_integral,
    chebyshev_polynomial_u_interpolate,
    chebyshev_polynomial_u_linspace,
    chebyshev_polynomial_u_mod,
    chebyshev_polynomial_u_multiply,
    chebyshev_polynomial_u_mulx,
    chebyshev_polynomial_u_negate,
    chebyshev_polynomial_u_points,
    chebyshev_polynomial_u_pow,
    chebyshev_polynomial_u_roots,
    chebyshev_polynomial_u_scale,
    chebyshev_polynomial_u_subtract,
    chebyshev_polynomial_u_to_polynomial,
    chebyshev_polynomial_u_trim,
    chebyshev_polynomial_u_vandermonde,
    chebyshev_polynomial_u_weight,
    polynomial_to_chebyshev_polynomial_u,
)
from ._chebyshev_polynomial_v import (
    ChebyshevPolynomialV,
    chebyshev_polynomial_v,
    chebyshev_polynomial_v_add,
    chebyshev_polynomial_v_antiderivative,
    chebyshev_polynomial_v_companion,
    chebyshev_polynomial_v_degree,
    chebyshev_polynomial_v_derivative,
    chebyshev_polynomial_v_div,
    chebyshev_polynomial_v_divmod,
    chebyshev_polynomial_v_equal,
    chebyshev_polynomial_v_evaluate,
    chebyshev_polynomial_v_fit,
    chebyshev_polynomial_v_from_roots,
    chebyshev_polynomial_v_integral,
    chebyshev_polynomial_v_interpolate,
    chebyshev_polynomial_v_mod,
    chebyshev_polynomial_v_multiply,
    chebyshev_polynomial_v_mulx,
    chebyshev_polynomial_v_negate,
    chebyshev_polynomial_v_points,
    chebyshev_polynomial_v_pow,
    chebyshev_polynomial_v_roots,
    chebyshev_polynomial_v_scale,
    chebyshev_polynomial_v_subtract,
    chebyshev_polynomial_v_to_polynomial,
    chebyshev_polynomial_v_trim,
    chebyshev_polynomial_v_vandermonde,
    chebyshev_polynomial_v_weight,
    polynomial_to_chebyshev_polynomial_v,
)
from ._degree_error import DegreeError
from ._exceptions import (
    DomainError,
    ParameterError,
    ParameterMismatchError,
)
from ._gegenbauer_polynomial_c import (
    GegenbauerPolynomialC,
    gegenbauer_polynomial_c,
    gegenbauer_polynomial_c_add,
    gegenbauer_polynomial_c_antiderivative,
    gegenbauer_polynomial_c_companion,
    gegenbauer_polynomial_c_degree,
    gegenbauer_polynomial_c_derivative,
    gegenbauer_polynomial_c_div,
    gegenbauer_polynomial_c_divmod,
    gegenbauer_polynomial_c_equal,
    gegenbauer_polynomial_c_evaluate,
    gegenbauer_polynomial_c_fit,
    gegenbauer_polynomial_c_from_roots,
    gegenbauer_polynomial_c_integral,
    gegenbauer_polynomial_c_interpolate,
    gegenbauer_polynomial_c_linspace,
    gegenbauer_polynomial_c_mod,
    gegenbauer_polynomial_c_multiply,
    gegenbauer_polynomial_c_mulx,
    gegenbauer_polynomial_c_negate,
    gegenbauer_polynomial_c_points,
    gegenbauer_polynomial_c_pow,
    gegenbauer_polynomial_c_roots,
    gegenbauer_polynomial_c_scale,
    gegenbauer_polynomial_c_subtract,
    gegenbauer_polynomial_c_to_polynomial,
    gegenbauer_polynomial_c_trim,
    gegenbauer_polynomial_c_vandermonde,
    gegenbauer_polynomial_c_weight,
    polynomial_to_gegenbauer_polynomial_c,
)
from ._hermite_polynomial_h import (
    HermitePolynomialH,
    hermite_polynomial_h,
    hermite_polynomial_h_add,
    hermite_polynomial_h_antiderivative,
    hermite_polynomial_h_companion,
    hermite_polynomial_h_degree,
    hermite_polynomial_h_derivative,
    hermite_polynomial_h_div,
    hermite_polynomial_h_divmod,
    hermite_polynomial_h_equal,
    hermite_polynomial_h_evaluate,
    hermite_polynomial_h_fit,
    hermite_polynomial_h_from_roots,
    hermite_polynomial_h_integral,
    hermite_polynomial_h_interpolate,
    hermite_polynomial_h_linspace,
    hermite_polynomial_h_mod,
    hermite_polynomial_h_multiply,
    hermite_polynomial_h_mulx,
    hermite_polynomial_h_negate,
    hermite_polynomial_h_points,
    hermite_polynomial_h_pow,
    hermite_polynomial_h_roots,
    hermite_polynomial_h_scale,
    hermite_polynomial_h_subtract,
    hermite_polynomial_h_to_polynomial,
    hermite_polynomial_h_trim,
    hermite_polynomial_h_vandermonde,
    hermite_polynomial_h_weight,
    polynomial_to_hermite_polynomial_h,
)
from ._hermite_polynomial_he import (
    HermitePolynomialHe,
    hermite_polynomial_he,
    hermite_polynomial_he_add,
    hermite_polynomial_he_antiderivative,
    hermite_polynomial_he_companion,
    hermite_polynomial_he_degree,
    hermite_polynomial_he_derivative,
    hermite_polynomial_he_div,
    hermite_polynomial_he_divmod,
    hermite_polynomial_he_equal,
    hermite_polynomial_he_evaluate,
    hermite_polynomial_he_fit,
    hermite_polynomial_he_from_roots,
    hermite_polynomial_he_integral,
    hermite_polynomial_he_interpolate,
    hermite_polynomial_he_linspace,
    hermite_polynomial_he_mod,
    hermite_polynomial_he_multiply,
    hermite_polynomial_he_mulx,
    hermite_polynomial_he_negate,
    hermite_polynomial_he_points,
    hermite_polynomial_he_pow,
    hermite_polynomial_he_roots,
    hermite_polynomial_he_scale,
    hermite_polynomial_he_subtract,
    hermite_polynomial_he_to_polynomial,
    hermite_polynomial_he_trim,
    hermite_polynomial_he_vandermonde,
    hermite_polynomial_he_weight,
    polynomial_to_hermite_polynomial_he,
)
from ._jacobi_polynomial_p import (
    JacobiPolynomialP,
    jacobi_polynomial_p,
    jacobi_polynomial_p_add,
    jacobi_polynomial_p_antiderivative,
    jacobi_polynomial_p_companion,
    jacobi_polynomial_p_degree,
    jacobi_polynomial_p_derivative,
    jacobi_polynomial_p_div,
    jacobi_polynomial_p_divmod,
    jacobi_polynomial_p_equal,
    jacobi_polynomial_p_evaluate,
    jacobi_polynomial_p_fit,
    jacobi_polynomial_p_from_roots,
    jacobi_polynomial_p_integral,
    jacobi_polynomial_p_interpolate,
    jacobi_polynomial_p_linspace,
    jacobi_polynomial_p_mod,
    jacobi_polynomial_p_multiply,
    jacobi_polynomial_p_mulx,
    jacobi_polynomial_p_negate,
    jacobi_polynomial_p_points,
    jacobi_polynomial_p_pow,
    jacobi_polynomial_p_roots,
    jacobi_polynomial_p_scale,
    jacobi_polynomial_p_subtract,
    jacobi_polynomial_p_to_polynomial,
    jacobi_polynomial_p_trim,
    jacobi_polynomial_p_vandermonde,
    jacobi_polynomial_p_weight,
    polynomial_to_jacobi_polynomial_p,
)
from ._laguerre_polynomial_l import (
    LaguerrePolynomialL,
    laguerre_polynomial_l,
    laguerre_polynomial_l_add,
    laguerre_polynomial_l_antiderivative,
    laguerre_polynomial_l_companion,
    laguerre_polynomial_l_degree,
    laguerre_polynomial_l_derivative,
    laguerre_polynomial_l_div,
    laguerre_polynomial_l_divmod,
    laguerre_polynomial_l_equal,
    laguerre_polynomial_l_evaluate,
    laguerre_polynomial_l_fit,
    laguerre_polynomial_l_from_roots,
    laguerre_polynomial_l_integral,
    laguerre_polynomial_l_interpolate,
    laguerre_polynomial_l_linspace,
    laguerre_polynomial_l_mod,
    laguerre_polynomial_l_multiply,
    laguerre_polynomial_l_mulx,
    laguerre_polynomial_l_negate,
    laguerre_polynomial_l_points,
    laguerre_polynomial_l_pow,
    laguerre_polynomial_l_roots,
    laguerre_polynomial_l_scale,
    laguerre_polynomial_l_subtract,
    laguerre_polynomial_l_to_polynomial,
    laguerre_polynomial_l_trim,
    laguerre_polynomial_l_vandermonde,
    laguerre_polynomial_l_weight,
    polynomial_to_laguerre_polynomial_l,
)
from ._legendre_polynomial_p import (
    LegendrePolynomialP,
    legendre_polynomial_p,
    legendre_polynomial_p_add,
    legendre_polynomial_p_antiderivative,
    legendre_polynomial_p_companion,
    legendre_polynomial_p_degree,
    legendre_polynomial_p_derivative,
    legendre_polynomial_p_div,
    legendre_polynomial_p_divmod,
    legendre_polynomial_p_equal,
    legendre_polynomial_p_evaluate,
    legendre_polynomial_p_fit,
    legendre_polynomial_p_from_roots,
    legendre_polynomial_p_integral,
    legendre_polynomial_p_interpolate,
    legendre_polynomial_p_linspace,
    legendre_polynomial_p_mod,
    legendre_polynomial_p_multiply,
    legendre_polynomial_p_mulx,
    legendre_polynomial_p_negate,
    legendre_polynomial_p_points,
    legendre_polynomial_p_pow,
    legendre_polynomial_p_roots,
    legendre_polynomial_p_scale,
    legendre_polynomial_p_subtract,
    legendre_polynomial_p_to_polynomial,
    legendre_polynomial_p_trim,
    legendre_polynomial_p_vandermonde,
    legendre_polynomial_p_weight,
    polynomial_to_legendre_polynomial_p,
)
from ._polynomial import (
    Polynomial,
    polynomial,
    polynomial_add,
    polynomial_antiderivative,
    polynomial_compose,
    polynomial_degree,
    polynomial_derivative,
    polynomial_div,
    polynomial_divmod,
    polynomial_equal,
    polynomial_evaluate,
    polynomial_fit,
    polynomial_from_roots,
    polynomial_integral,
    polynomial_mod,
    polynomial_multiply,
    polynomial_negate,
    polynomial_pow,
    polynomial_roots,
    polynomial_scale,
    polynomial_subtract,
    polynomial_trim,
    polynomial_vandermonde,
)
from ._polynomial_error import (
    PolynomialError,
)

__all__ = [
    "ChebyshevPolynomialT",
    "chebyshev_polynomial_t",
    "chebyshev_polynomial_t_add",
    "chebyshev_polynomial_t_antiderivative",
    "chebyshev_polynomial_t_companion",
    "chebyshev_polynomial_t_degree",
    "chebyshev_polynomial_t_derivative",
    "chebyshev_polynomial_t_div",
    "chebyshev_polynomial_t_divmod",
    "chebyshev_polynomial_t_equal",
    "chebyshev_polynomial_t_evaluate",
    "chebyshev_polynomial_t_fit",
    "chebyshev_polynomial_t_from_roots",
    "chebyshev_polynomial_t_integral",
    "chebyshev_polynomial_t_interpolate",
    "chebyshev_polynomial_t_mod",
    "chebyshev_polynomial_t_multiply",
    "chebyshev_polynomial_t_mulx",
    "chebyshev_polynomial_t_negate",
    "chebyshev_polynomial_t_points",
    "chebyshev_polynomial_t_pow",
    "chebyshev_polynomial_t_roots",
    "chebyshev_polynomial_t_scale",
    "chebyshev_polynomial_t_subtract",
    "chebyshev_polynomial_t_to_polynomial",
    "chebyshev_polynomial_t_trim",
    "chebyshev_polynomial_t_vandermonde",
    "chebyshev_polynomial_t_weight",
    "polynomial_to_chebyshev_polynomial_t",
    "ChebyshevPolynomialU",
    "chebyshev_polynomial_u",
    "chebyshev_polynomial_u_add",
    "chebyshev_polynomial_u_antiderivative",
    "chebyshev_polynomial_u_companion",
    "chebyshev_polynomial_u_degree",
    "chebyshev_polynomial_u_derivative",
    "chebyshev_polynomial_u_div",
    "chebyshev_polynomial_u_divmod",
    "chebyshev_polynomial_u_equal",
    "chebyshev_polynomial_u_evaluate",
    "chebyshev_polynomial_u_fit",
    "chebyshev_polynomial_u_from_roots",
    "chebyshev_polynomial_u_integral",
    "chebyshev_polynomial_u_interpolate",
    "chebyshev_polynomial_u_linspace",
    "chebyshev_polynomial_u_mod",
    "chebyshev_polynomial_u_multiply",
    "chebyshev_polynomial_u_mulx",
    "chebyshev_polynomial_u_negate",
    "chebyshev_polynomial_u_points",
    "chebyshev_polynomial_u_pow",
    "chebyshev_polynomial_u_roots",
    "chebyshev_polynomial_u_scale",
    "chebyshev_polynomial_u_subtract",
    "chebyshev_polynomial_u_to_polynomial",
    "chebyshev_polynomial_u_trim",
    "chebyshev_polynomial_u_vandermonde",
    "chebyshev_polynomial_u_weight",
    "polynomial_to_chebyshev_polynomial_u",
    "ChebyshevPolynomialV",
    "chebyshev_polynomial_v",
    "chebyshev_polynomial_v_add",
    "chebyshev_polynomial_v_antiderivative",
    "chebyshev_polynomial_v_companion",
    "chebyshev_polynomial_v_degree",
    "chebyshev_polynomial_v_derivative",
    "chebyshev_polynomial_v_div",
    "chebyshev_polynomial_v_divmod",
    "chebyshev_polynomial_v_equal",
    "chebyshev_polynomial_v_evaluate",
    "chebyshev_polynomial_v_fit",
    "chebyshev_polynomial_v_from_roots",
    "chebyshev_polynomial_v_integral",
    "chebyshev_polynomial_v_interpolate",
    "chebyshev_polynomial_v_mod",
    "chebyshev_polynomial_v_multiply",
    "chebyshev_polynomial_v_mulx",
    "chebyshev_polynomial_v_negate",
    "chebyshev_polynomial_v_points",
    "chebyshev_polynomial_v_pow",
    "chebyshev_polynomial_v_roots",
    "chebyshev_polynomial_v_scale",
    "chebyshev_polynomial_v_subtract",
    "chebyshev_polynomial_v_to_polynomial",
    "chebyshev_polynomial_v_trim",
    "chebyshev_polynomial_v_vandermonde",
    "chebyshev_polynomial_v_weight",
    "polynomial_to_chebyshev_polynomial_v",
    "DegreeError",
    "DomainError",
    "GegenbauerPolynomialC",
    "gegenbauer_polynomial_c",
    "gegenbauer_polynomial_c_add",
    "gegenbauer_polynomial_c_antiderivative",
    "gegenbauer_polynomial_c_companion",
    "gegenbauer_polynomial_c_degree",
    "gegenbauer_polynomial_c_derivative",
    "gegenbauer_polynomial_c_div",
    "gegenbauer_polynomial_c_divmod",
    "gegenbauer_polynomial_c_equal",
    "gegenbauer_polynomial_c_evaluate",
    "gegenbauer_polynomial_c_fit",
    "gegenbauer_polynomial_c_from_roots",
    "gegenbauer_polynomial_c_integral",
    "gegenbauer_polynomial_c_interpolate",
    "gegenbauer_polynomial_c_linspace",
    "gegenbauer_polynomial_c_mod",
    "gegenbauer_polynomial_c_multiply",
    "gegenbauer_polynomial_c_mulx",
    "gegenbauer_polynomial_c_negate",
    "gegenbauer_polynomial_c_points",
    "gegenbauer_polynomial_c_pow",
    "gegenbauer_polynomial_c_roots",
    "gegenbauer_polynomial_c_scale",
    "gegenbauer_polynomial_c_subtract",
    "gegenbauer_polynomial_c_to_polynomial",
    "gegenbauer_polynomial_c_trim",
    "gegenbauer_polynomial_c_vandermonde",
    "gegenbauer_polynomial_c_weight",
    "polynomial_to_gegenbauer_polynomial_c",
    "HermitePolynomialH",
    "hermite_polynomial_h",
    "hermite_polynomial_h_add",
    "hermite_polynomial_h_antiderivative",
    "hermite_polynomial_h_companion",
    "hermite_polynomial_h_degree",
    "hermite_polynomial_h_derivative",
    "hermite_polynomial_h_div",
    "hermite_polynomial_h_divmod",
    "hermite_polynomial_h_equal",
    "hermite_polynomial_h_evaluate",
    "hermite_polynomial_h_fit",
    "hermite_polynomial_h_from_roots",
    "hermite_polynomial_h_integral",
    "hermite_polynomial_h_interpolate",
    "hermite_polynomial_h_linspace",
    "hermite_polynomial_h_mod",
    "hermite_polynomial_h_multiply",
    "hermite_polynomial_h_mulx",
    "hermite_polynomial_h_negate",
    "hermite_polynomial_h_points",
    "hermite_polynomial_h_pow",
    "hermite_polynomial_h_roots",
    "hermite_polynomial_h_scale",
    "hermite_polynomial_h_subtract",
    "hermite_polynomial_h_to_polynomial",
    "hermite_polynomial_h_trim",
    "hermite_polynomial_h_vandermonde",
    "hermite_polynomial_h_weight",
    "polynomial_to_hermite_polynomial_h",
    "JacobiPolynomialP",
    "jacobi_polynomial_p",
    "jacobi_polynomial_p_add",
    "jacobi_polynomial_p_antiderivative",
    "jacobi_polynomial_p_companion",
    "jacobi_polynomial_p_degree",
    "jacobi_polynomial_p_derivative",
    "jacobi_polynomial_p_div",
    "jacobi_polynomial_p_divmod",
    "jacobi_polynomial_p_equal",
    "jacobi_polynomial_p_evaluate",
    "jacobi_polynomial_p_fit",
    "jacobi_polynomial_p_from_roots",
    "jacobi_polynomial_p_integral",
    "jacobi_polynomial_p_interpolate",
    "jacobi_polynomial_p_linspace",
    "jacobi_polynomial_p_mod",
    "jacobi_polynomial_p_multiply",
    "jacobi_polynomial_p_mulx",
    "jacobi_polynomial_p_negate",
    "jacobi_polynomial_p_points",
    "jacobi_polynomial_p_pow",
    "jacobi_polynomial_p_roots",
    "jacobi_polynomial_p_scale",
    "jacobi_polynomial_p_subtract",
    "jacobi_polynomial_p_to_polynomial",
    "jacobi_polynomial_p_trim",
    "jacobi_polynomial_p_vandermonde",
    "jacobi_polynomial_p_weight",
    "polynomial_to_jacobi_polynomial_p",
    "HermitePolynomialHe",
    "hermite_polynomial_he",
    "hermite_polynomial_he_add",
    "hermite_polynomial_he_antiderivative",
    "hermite_polynomial_he_companion",
    "hermite_polynomial_he_degree",
    "hermite_polynomial_he_derivative",
    "hermite_polynomial_he_div",
    "hermite_polynomial_he_divmod",
    "hermite_polynomial_he_equal",
    "hermite_polynomial_he_evaluate",
    "hermite_polynomial_he_fit",
    "hermite_polynomial_he_from_roots",
    "hermite_polynomial_he_integral",
    "hermite_polynomial_he_interpolate",
    "hermite_polynomial_he_linspace",
    "hermite_polynomial_he_mod",
    "hermite_polynomial_he_multiply",
    "hermite_polynomial_he_mulx",
    "hermite_polynomial_he_negate",
    "hermite_polynomial_he_points",
    "hermite_polynomial_he_pow",
    "hermite_polynomial_he_roots",
    "hermite_polynomial_he_scale",
    "hermite_polynomial_he_subtract",
    "hermite_polynomial_he_to_polynomial",
    "hermite_polynomial_he_trim",
    "hermite_polynomial_he_vandermonde",
    "hermite_polynomial_he_weight",
    "polynomial_to_hermite_polynomial_he",
    "LaguerrePolynomialL",
    "laguerre_polynomial_l",
    "laguerre_polynomial_l_add",
    "laguerre_polynomial_l_antiderivative",
    "laguerre_polynomial_l_companion",
    "laguerre_polynomial_l_degree",
    "laguerre_polynomial_l_derivative",
    "laguerre_polynomial_l_div",
    "laguerre_polynomial_l_divmod",
    "laguerre_polynomial_l_equal",
    "laguerre_polynomial_l_evaluate",
    "laguerre_polynomial_l_fit",
    "laguerre_polynomial_l_from_roots",
    "laguerre_polynomial_l_integral",
    "laguerre_polynomial_l_interpolate",
    "laguerre_polynomial_l_linspace",
    "laguerre_polynomial_l_mod",
    "laguerre_polynomial_l_multiply",
    "laguerre_polynomial_l_mulx",
    "laguerre_polynomial_l_negate",
    "laguerre_polynomial_l_points",
    "laguerre_polynomial_l_pow",
    "laguerre_polynomial_l_roots",
    "laguerre_polynomial_l_scale",
    "laguerre_polynomial_l_subtract",
    "laguerre_polynomial_l_to_polynomial",
    "laguerre_polynomial_l_trim",
    "laguerre_polynomial_l_vandermonde",
    "laguerre_polynomial_l_weight",
    "polynomial_to_laguerre_polynomial_l",
    "LegendrePolynomialP",
    "legendre_polynomial_p",
    "legendre_polynomial_p_add",
    "legendre_polynomial_p_antiderivative",
    "legendre_polynomial_p_companion",
    "legendre_polynomial_p_degree",
    "legendre_polynomial_p_derivative",
    "legendre_polynomial_p_div",
    "legendre_polynomial_p_divmod",
    "legendre_polynomial_p_equal",
    "legendre_polynomial_p_evaluate",
    "legendre_polynomial_p_fit",
    "legendre_polynomial_p_from_roots",
    "legendre_polynomial_p_integral",
    "legendre_polynomial_p_interpolate",
    "legendre_polynomial_p_linspace",
    "legendre_polynomial_p_mod",
    "legendre_polynomial_p_multiply",
    "legendre_polynomial_p_mulx",
    "legendre_polynomial_p_negate",
    "legendre_polynomial_p_points",
    "legendre_polynomial_p_pow",
    "legendre_polynomial_p_roots",
    "legendre_polynomial_p_scale",
    "legendre_polynomial_p_subtract",
    "legendre_polynomial_p_to_polynomial",
    "legendre_polynomial_p_trim",
    "legendre_polynomial_p_vandermonde",
    "legendre_polynomial_p_weight",
    "polynomial_to_legendre_polynomial_p",
    "ParameterError",
    "ParameterMismatchError",
    "Polynomial",
    "PolynomialError",
    "polynomial",
    "polynomial_add",
    "polynomial_antiderivative",
    "polynomial_compose",
    "polynomial_degree",
    "polynomial_derivative",
    "polynomial_div",
    "polynomial_divmod",
    "polynomial_equal",
    "polynomial_evaluate",
    "polynomial_fit",
    "polynomial_from_roots",
    "polynomial_integral",
    "polynomial_mod",
    "polynomial_multiply",
    "polynomial_negate",
    "polynomial_pow",
    "polynomial_roots",
    "polynomial_scale",
    "polynomial_subtract",
    "polynomial_trim",
    "polynomial_vandermonde",
]
