#include <torch/library.h>

#include <torchscience/csrc/autocast/special_functions.h>
#include <torchscience/csrc/autograd/special_functions.h>
#include <torchscience/csrc/cpu/special_functions.h>
#include <torchscience/csrc/meta/special_functions.h>
#include <torchscience/csrc/quantized/cpu/special_functions.h>
#include <torchscience/csrc/sparse/coo/cpu/special_functions.h>
#include <torchscience/csrc/sparse/csr/cpu/special_functions.h>

TORCH_LIBRARY_FRAGMENT(torchscience, module) {
  module.def("_airy_ai(Tensor input) -> Tensor");
  module.def("_airy_ai_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_airy_ai_derivative(Tensor input) -> Tensor");
  module.def("_airy_ai_derivative_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_airy_bi(Tensor input) -> Tensor");
  module.def("_airy_bi_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_airy_bi_derivative(Tensor input) -> Tensor");
  module.def("_airy_bi_derivative_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_associated_legendre_p(Tensor n, Tensor m, Tensor x) -> Tensor");
  module.def("_associated_legendre_p_backward(Tensor grad_output, Tensor n, Tensor m, Tensor x) -> (Tensor, Tensor, Tensor)");
  module.def("_bessel_j(Tensor nu, Tensor x) -> Tensor");
  module.def("_bessel_j_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_bessel_j_derivative(Tensor nu, Tensor x) -> Tensor");
  module.def("_bessel_j_derivative_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_bessel_y(Tensor nu, Tensor x) -> Tensor");
  module.def("_bessel_y_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_bessel_y_derivative(Tensor nu, Tensor x) -> Tensor");
  module.def("_bessel_y_derivative_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_bernoulli_number_b(Tensor input) -> Tensor");
  module.def("_bernoulli_number_b_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_bernoulli_polynomial_b(Tensor n, Tensor x) -> Tensor");
  module.def("_bernoulli_polynomial_b_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_beta(Tensor a, Tensor b) -> Tensor");
  module.def("_beta_backward(Tensor grad_output, Tensor a, Tensor b) -> (Tensor, Tensor)");
  module.def("_binomial_coefficient(Tensor n, Tensor k) -> Tensor");
  module.def("_binomial_coefficient_backward(Tensor grad_output, Tensor n, Tensor k) -> (Tensor, Tensor)");
  module.def("_bulirsch_elliptic_integral_el1(Tensor x, Tensor kc) -> Tensor");
  module.def("_bulirsch_elliptic_integral_el1_backward(Tensor grad_output, Tensor x, Tensor kc) -> (Tensor, Tensor)");
  module.def("_chebyshev_polynomial_t(Tensor n, Tensor x) -> Tensor");
  module.def("_chebyshev_polynomial_t_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_chebyshev_polynomial_u(Tensor n, Tensor x) -> Tensor");
  module.def("_chebyshev_polynomial_u_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_chebyshev_polynomial_v(Tensor n, Tensor x) -> Tensor");
  module.def("_chebyshev_polynomial_v_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_chebyshev_polynomial_w(Tensor n, Tensor x) -> Tensor");
  module.def("_chebyshev_polynomial_w_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_shifted_chebyshev_polynomial_t(Tensor n, Tensor x) -> Tensor");
  module.def("_shifted_chebyshev_polynomial_t_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_shifted_chebyshev_polynomial_u(Tensor n, Tensor x) -> Tensor");
  module.def("_shifted_chebyshev_polynomial_u_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_shifted_chebyshev_polynomial_v(Tensor n, Tensor x) -> Tensor");
  module.def("_shifted_chebyshev_polynomial_v_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_shifted_chebyshev_polynomial_w(Tensor n, Tensor x) -> Tensor");
  module.def("_shifted_chebyshev_polynomial_w_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_hermite_polynomial_he(Tensor n, Tensor x) -> Tensor");
  module.def("_hermite_polynomial_he_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_hermite_polynomial_h(Tensor n, Tensor x) -> Tensor");
  module.def("_hermite_polynomial_h_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_confluent_hypergeometric_1_f_1(Tensor a, Tensor b, Tensor z) -> Tensor");
  module.def("_confluent_hypergeometric_1_f_1_backward(Tensor grad_output, Tensor a, Tensor b, Tensor z) -> (Tensor, Tensor, Tensor)");
  module.def("_carlson_elliptic_integral_r_c(Tensor x, Tensor y) -> Tensor");
  module.def("_carlson_elliptic_integral_r_c_backward(Tensor grad_output, Tensor x, Tensor y) -> (Tensor, Tensor)");
  module.def("_carlson_elliptic_integral_r_d(Tensor x, Tensor y, Tensor z) -> Tensor");
  module.def("_carlson_elliptic_integral_r_d_backward(Tensor grad_output, Tensor x, Tensor y, Tensor z) -> (Tensor, Tensor, Tensor)");
  module.def("_carlson_elliptic_integral_r_e(Tensor x, Tensor y, Tensor z) -> Tensor");
  module.def("_carlson_elliptic_integral_r_e_backward(Tensor grad_output, Tensor x, Tensor y, Tensor z) -> (Tensor, Tensor, Tensor)");
  module.def("_carlson_elliptic_integral_r_j(Tensor x, Tensor y, Tensor z, Tensor p) -> Tensor");
  module.def("_carlson_elliptic_integral_r_j_backward(Tensor grad_output, Tensor x, Tensor y, Tensor z, Tensor p) -> (Tensor, Tensor, Tensor, Tensor)");
  module.def("_carlson_elliptic_integral_r_k(Tensor x, Tensor y, Tensor z) -> Tensor");
  module.def("_carlson_elliptic_integral_r_k_backward(Tensor grad_output, Tensor x, Tensor y, Tensor z) -> (Tensor, Tensor, Tensor)");
  module.def("_carlson_elliptic_integral_r_m(Tensor x, Tensor y, Tensor z) -> Tensor");
  module.def("_carlson_elliptic_integral_r_m_backward(Tensor grad_output, Tensor x, Tensor y, Tensor z) -> (Tensor, Tensor, Tensor)");
  module.def("_carlson_elliptic_r_c(Tensor x, Tensor y) -> Tensor");
  module.def("_carlson_elliptic_r_c_backward(Tensor grad_output, Tensor x, Tensor y) -> (Tensor, Tensor)");
  module.def("_complete_carlson_elliptic_r_f(Tensor x, Tensor y) -> Tensor");
  module.def("_complete_carlson_elliptic_r_f_backward(Tensor grad_output, Tensor x, Tensor y) -> (Tensor, Tensor)");
  module.def("_complete_carlson_elliptic_r_g(Tensor x, Tensor y) -> Tensor");
  module.def("_complete_carlson_elliptic_r_g_backward(Tensor grad_output, Tensor x, Tensor y) -> (Tensor, Tensor)");
  module.def("_complete_elliptic_integral_e(Tensor input) -> Tensor");
  module.def("_complete_elliptic_integral_e_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_complete_elliptic_integral_k(Tensor input) -> Tensor");
  module.def("_complete_elliptic_integral_k_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_complete_elliptic_integral_pi(Tensor n, Tensor k) -> Tensor");
  module.def("_complete_elliptic_integral_pi_backward(Tensor grad_output, Tensor n, Tensor k) -> (Tensor, Tensor)");
  module.def("_complete_legendre_elliptic_integral_d(Tensor input) -> Tensor");
  module.def("_complete_legendre_elliptic_integral_d_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_confluent_hypergeometric_0_f_1(Tensor b, Tensor z) -> Tensor");
  module.def("_confluent_hypergeometric_0_f_1_backward(Tensor grad_output, Tensor b, Tensor z) -> (Tensor, Tensor)");
  module.def("_cos_pi(Tensor input) -> Tensor");
  module.def("_cos_pi_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_cosine_integral_ci(Tensor input) -> Tensor");
  module.def("_cosine_integral_ci_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_cosine_integral_cin(Tensor input) -> Tensor");
  module.def("_cosine_integral_cin_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_digamma(Tensor input) -> Tensor");
  module.def("_digamma_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_double_factorial(Tensor input) -> Tensor");
  module.def("_double_factorial_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_erf(Tensor input) -> Tensor");
  module.def("_erf_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_erfc(Tensor input) -> Tensor");
  module.def("_erfc_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_euler_number_e(Tensor input) -> Tensor");
  module.def("_euler_number_e_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_euler_polynomial_e(Tensor n, Tensor x) -> Tensor");
  module.def("_euler_polynomial_e_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_euler_totient_phi(Tensor input) -> Tensor");
  module.def("_euler_totient_phi_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_exponential_integral_e(Tensor n, Tensor x) -> Tensor");
  module.def("_exponential_integral_e_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_exponential_integral_e_1(Tensor input) -> Tensor");
  module.def("_exponential_integral_e_1_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_exponential_integral_ei(Tensor input) -> Tensor");
  module.def("_exponential_integral_ei_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_factorial(Tensor input) -> Tensor");
  module.def("_factorial_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_falling_factorial(Tensor x, Tensor n) -> Tensor");
  module.def("_falling_factorial_backward(Tensor grad_output, Tensor x, Tensor n) -> (Tensor, Tensor)");
  module.def("_fibonacci_number_f(Tensor input) -> Tensor");
  module.def("_fibonacci_number_f_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_gamma(Tensor input) -> Tensor");
  module.def("_gamma_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_hankel_h_1(Tensor nu, Tensor x) -> Tensor");
  module.def("_hankel_h_1_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_hankel_h_2(Tensor nu, Tensor x) -> Tensor");
  module.def("_hankel_h_2_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_hyperbolic_cosine_integral_chi(Tensor input) -> Tensor");
  module.def("_hyperbolic_cosine_integral_chi_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_hyperbolic_sine_integral_shi(Tensor input) -> Tensor");
  module.def("_hyperbolic_sine_integral_shi_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_incomplete_elliptic_integral_e(Tensor phi, Tensor k) -> Tensor");
  module.def("_incomplete_elliptic_integral_e_backward(Tensor grad_output, Tensor phi, Tensor k) -> (Tensor, Tensor)");
  module.def("_incomplete_elliptic_integral_f(Tensor phi, Tensor k) -> Tensor");
  module.def("_incomplete_elliptic_integral_f_backward(Tensor grad_output, Tensor phi, Tensor k) -> (Tensor, Tensor)");
  module.def("_incomplete_legendre_elliptic_integral_d(Tensor phi, Tensor k) -> Tensor");
  module.def("_incomplete_legendre_elliptic_integral_d_backward(Tensor grad_output, Tensor phi, Tensor k) -> (Tensor, Tensor)");
  module.def("_legendre_elliptic_integral_pi(Tensor n, Tensor phi, Tensor k) -> Tensor");
  module.def("_legendre_elliptic_integral_pi_backward(Tensor grad_output, Tensor n, Tensor phi, Tensor k) -> (Tensor, Tensor, Tensor)");
  module.def("_inverse_erf(Tensor input) -> Tensor");
  module.def("_inverse_erf_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_inverse_erfc(Tensor input) -> Tensor");
  module.def("_inverse_erfc_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_jacobi_amplitude_am(Tensor u, Tensor k) -> Tensor");
  module.def("_jacobi_amplitude_am_backward(Tensor grad_output, Tensor u, Tensor k) -> (Tensor, Tensor)");
  module.def("_jacobi_elliptic_cd(Tensor u, Tensor k) -> Tensor");
  module.def("_jacobi_elliptic_cd_backward(Tensor grad_output, Tensor u, Tensor k) -> (Tensor, Tensor)");
  module.def("_jacobi_elliptic_cn(Tensor u, Tensor k) -> Tensor");
  module.def("_jacobi_elliptic_cn_backward(Tensor grad_output, Tensor u, Tensor k) -> (Tensor, Tensor)");
  module.def("_jacobi_elliptic_dn(Tensor u, Tensor k) -> Tensor");
  module.def("_jacobi_elliptic_dn_backward(Tensor grad_output, Tensor u, Tensor k) -> (Tensor, Tensor)");
  module.def("_jacobi_elliptic_sc(Tensor u, Tensor k) -> Tensor");
  module.def("_jacobi_elliptic_sc_backward(Tensor grad_output, Tensor u, Tensor k) -> (Tensor, Tensor)");
  module.def("_jacobi_elliptic_sd(Tensor u, Tensor k) -> Tensor");
  module.def("_jacobi_elliptic_sd_backward(Tensor grad_output, Tensor u, Tensor k) -> (Tensor, Tensor)");
  module.def("_jacobi_elliptic_sn(Tensor u, Tensor k) -> Tensor");
  module.def("_jacobi_elliptic_sn_backward(Tensor grad_output, Tensor u, Tensor k) -> (Tensor, Tensor)");
  module.def("_inverse_jacobi_elliptic_cd(Tensor x, Tensor k) -> Tensor");
  module.def("_inverse_jacobi_elliptic_cd_backward(Tensor grad_output, Tensor x, Tensor k) -> (Tensor, Tensor)");
  module.def("_inverse_jacobi_elliptic_cn(Tensor x, Tensor k) -> Tensor");
  module.def("_inverse_jacobi_elliptic_cn_backward(Tensor grad_output, Tensor x, Tensor k) -> (Tensor, Tensor)");
  module.def("_inverse_jacobi_elliptic_dn(Tensor x, Tensor k) -> Tensor");
  module.def("_inverse_jacobi_elliptic_dn_backward(Tensor grad_output, Tensor x, Tensor k) -> (Tensor, Tensor)");
  module.def("_inverse_jacobi_elliptic_sc(Tensor x, Tensor k) -> Tensor");
  module.def("_inverse_jacobi_elliptic_sc_backward(Tensor grad_output, Tensor x, Tensor k) -> (Tensor, Tensor)");
  module.def("_inverse_jacobi_elliptic_sd(Tensor x, Tensor k) -> Tensor");
  module.def("_inverse_jacobi_elliptic_sd_backward(Tensor grad_output, Tensor x, Tensor k) -> (Tensor, Tensor)");
  module.def("_inverse_jacobi_elliptic_sn(Tensor x, Tensor k) -> Tensor");
  module.def("_inverse_jacobi_elliptic_sn_backward(Tensor grad_output, Tensor x, Tensor k) -> (Tensor, Tensor)");
  module.def("_legendre_p(Tensor n, Tensor x) -> Tensor");
  module.def("_legendre_p_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_legendre_q(Tensor n, Tensor x) -> Tensor");
  module.def("_legendre_q_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_jacobi_theta_1(Tensor z, Tensor q) -> Tensor");
  module.def("_jacobi_theta_1_backward(Tensor grad_output, Tensor z, Tensor q) -> (Tensor, Tensor)");
  module.def("_jacobi_theta_2(Tensor z, Tensor q) -> Tensor");
  module.def("_jacobi_theta_2_backward(Tensor grad_output, Tensor z, Tensor q) -> (Tensor, Tensor)");
  module.def("_jacobi_theta_3(Tensor z, Tensor q) -> Tensor");
  module.def("_jacobi_theta_3_backward(Tensor grad_output, Tensor z, Tensor q) -> (Tensor, Tensor)");
  module.def("_jacobi_theta_4(Tensor z, Tensor q) -> Tensor");
  module.def("_jacobi_theta_4_backward(Tensor grad_output, Tensor z, Tensor q) -> (Tensor, Tensor)");
  module.def("_log_beta(Tensor a, Tensor b) -> Tensor");
  module.def("_log_beta_backward(Tensor grad_output, Tensor a, Tensor b) -> (Tensor, Tensor)");
  module.def("_log_gamma(Tensor input) -> Tensor");
  module.def("_log_gamma_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_logarithmic_integral_li(Tensor input) -> Tensor");
  module.def("_logarithmic_integral_li_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_mobius_mu(Tensor input) -> Tensor");
  module.def("_mobius_mu_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_liouville_lambda(Tensor input) -> Tensor");
  module.def("_liouville_lambda_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_modified_bessel_i(Tensor nu, Tensor x) -> Tensor");
  module.def("_modified_bessel_i_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_modified_bessel_i_derivative(Tensor nu, Tensor x) -> Tensor");
  module.def("_modified_bessel_i_derivative_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_modified_bessel_k(Tensor nu, Tensor x) -> Tensor");
  module.def("_modified_bessel_k_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_modified_bessel_k_derivative(Tensor nu, Tensor x) -> Tensor");
  module.def("_modified_bessel_k_derivative_backward(Tensor grad_output, Tensor nu, Tensor x) -> (Tensor, Tensor)");
  module.def("_neville_theta_c(Tensor k, Tensor u) -> Tensor");
  module.def("_neville_theta_c_backward(Tensor grad_output, Tensor k, Tensor u) -> (Tensor, Tensor)");
  module.def("_neville_theta_d(Tensor k, Tensor u) -> Tensor");
  module.def("_neville_theta_d_backward(Tensor grad_output, Tensor k, Tensor u) -> (Tensor, Tensor)");
  module.def("_neville_theta_n(Tensor k, Tensor u) -> Tensor");
  module.def("_neville_theta_n_backward(Tensor grad_output, Tensor k, Tensor u) -> (Tensor, Tensor)");
  module.def("_neville_theta_s(Tensor k, Tensor u) -> Tensor");
  module.def("_neville_theta_s_backward(Tensor grad_output, Tensor k, Tensor u) -> (Tensor, Tensor)");
  module.def("_prime_number_p(Tensor input) -> Tensor");
  module.def("_prime_number_p_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_riemann_zeta(Tensor input) -> Tensor");
  module.def("_riemann_zeta_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_rising_factorial(Tensor x, Tensor n) -> Tensor");
  module.def("_rising_factorial_backward(Tensor grad_output, Tensor x, Tensor n) -> (Tensor, Tensor)");
  module.def("_sin_pi(Tensor input) -> Tensor");
  module.def("_sin_pi_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_sinc_pi(Tensor input) -> Tensor");
  module.def("_sinc_pi_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_sine_integral_sin(Tensor input) -> Tensor");
  module.def("_sine_integral_sin_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_sine_integral_si(Tensor input) -> Tensor");
  module.def("_sine_integral_si_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_sinhc_pi(Tensor input) -> Tensor");
  module.def("_sinhc_pi_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_spherical_bessel_j(Tensor n, Tensor x) -> Tensor");
  module.def("_spherical_bessel_j_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_spherical_bessel_y(Tensor n, Tensor x) -> Tensor");
  module.def("_spherical_bessel_y_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_spherical_hankel_h_1(Tensor n, Tensor x) -> Tensor");
  module.def("_spherical_hankel_h_1_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_spherical_hankel_h_2(Tensor n, Tensor x) -> Tensor");
  module.def("_spherical_hankel_h_2_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_spherical_modified_bessel_i(Tensor n, Tensor x) -> Tensor");
  module.def("_spherical_modified_bessel_i_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_spherical_modified_bessel_k(Tensor n, Tensor x) -> Tensor");
  module.def("_spherical_modified_bessel_k_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
  module.def("_stirling_number_s_1(Tensor n, Tensor k) -> Tensor");
  module.def("_stirling_number_s_1_backward(Tensor grad_output, Tensor n, Tensor k) -> (Tensor, Tensor)");
  module.def("_stirling_number_s_2(Tensor n, Tensor k) -> Tensor");
  module.def("_stirling_number_s_2_backward(Tensor grad_output, Tensor n, Tensor k) -> (Tensor, Tensor)");
  module.def("_tangent_number_t(Tensor input) -> Tensor");
  module.def("_tangent_number_t_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_trigamma(Tensor input) -> Tensor");
  module.def("_trigamma_backward(Tensor grad_output, Tensor input) -> Tensor");
  module.def("_kelvin_ber(Tensor v, Tensor x) -> Tensor");
  module.def("_kelvin_ber_backward(Tensor grad_output, Tensor v, Tensor x) -> (Tensor, Tensor)");
  module.def("_kelvin_bei(Tensor v, Tensor x) -> Tensor");
  module.def("_kelvin_bei_backward(Tensor grad_output, Tensor v, Tensor x) -> (Tensor, Tensor)");
  module.def("_kelvin_ker(Tensor v, Tensor x) -> Tensor");
  module.def("_kelvin_ker_backward(Tensor grad_output, Tensor v, Tensor x) -> (Tensor, Tensor)");
  module.def("_kelvin_kei(Tensor v, Tensor x) -> Tensor");
  module.def("_kelvin_kei_backward(Tensor grad_output, Tensor v, Tensor x) -> (Tensor, Tensor)");
  module.def("_polygamma(Tensor n, Tensor x) -> Tensor");
  module.def("_polygamma_backward(Tensor grad_output, Tensor n, Tensor x) -> (Tensor, Tensor)");
}
