#pragma once

#include "macros.h"

TORCHSCIENCE_META_POINTWISE_UNARY_OPERATOR(gamma, z)
TORCHSCIENCE_META_POINTWISE_UNARY_OPERATOR(digamma, z)
TORCHSCIENCE_META_POINTWISE_BINARY_OPERATOR(beta, a, b)
TORCHSCIENCE_META_POINTWISE_BINARY_OPERATOR(chebyshev_polynomial_t, x, n)
TORCHSCIENCE_META_POINTWISE_TERNARY_OPERATOR(incomplete_beta, x, a, b)
TORCHSCIENCE_META_POINTWISE_QUATERNARY_OPERATOR(hypergeometric_2_f_1, a, b, c, z)
