#pragma once

#include <torchscience/csrc/autocast/special_functions/airy_ai.h>
#include <torchscience/csrc/autocast/special_functions/airy_bi.h>
#include <torchscience/csrc/autocast/special_functions/bessel_j.h>
#include <torchscience/csrc/autocast/special_functions/bessel_y.h>
#include <torchscience/csrc/autocast/special_functions/beta.h>
#include <torchscience/csrc/autocast/special_functions/cos_pi.h>
#include <torchscience/csrc/autocast/special_functions/cosine_integral_ci.h>
#include <torchscience/csrc/autocast/special_functions/digamma.h>
#include <torchscience/csrc/autocast/special_functions/erf.h>
#include <torchscience/csrc/autocast/special_functions/erfc.h>
#include <torchscience/csrc/autocast/special_functions/exponential_integral_e.h>
#include <torchscience/csrc/autocast/special_functions/exponential_integral_ei.h>
#include <torchscience/csrc/autocast/special_functions/gamma.h>
#include <torchscience/csrc/autocast/special_functions/hyperbolic_cosine_integral_chi.h>
#include <torchscience/csrc/autocast/special_functions/hyperbolic_sine_integral_shi.h>
#include <torchscience/csrc/autocast/special_functions/inverse_erf.h>
#include <torchscience/csrc/autocast/special_functions/inverse_erfc.h>
#include <torchscience/csrc/autocast/special_functions/log_gamma.h>
#include <torchscience/csrc/autocast/special_functions/modified_bessel_i.h>
#include <torchscience/csrc/autocast/special_functions/modified_bessel_k.h>
#include <torchscience/csrc/autocast/special_functions/sin_pi.h>
#include <torchscience/csrc/autocast/special_functions/sinc_pi.h>
#include <torchscience/csrc/autocast/special_functions/sinhc_pi.h>
#include <torchscience/csrc/autocast/special_functions/spherical_bessel_j.h>
#include <torchscience/csrc/autocast/special_functions/spherical_bessel_y.h>
#include <torchscience/csrc/autocast/special_functions/spherical_modified_bessel_i.h>
#include <torchscience/csrc/autocast/special_functions/spherical_modified_bessel_k.h>
#include <torchscience/csrc/autocast/special_functions/trigamma.h>
