#pragma once

#include "macros.h"

TORCHSCIENCE_AUTOCAST_POINTWISE_UNARY_OPERATOR(gamma, z)
TORCHSCIENCE_AUTOCAST_POINTWISE_UNARY_OPERATOR(digamma, z)
TORCHSCIENCE_AUTOCAST_POINTWISE_UNARY_OPERATOR(trigamma, z)
TORCHSCIENCE_AUTOCAST_POINTWISE_BINARY_OPERATOR(beta, a, b)
TORCHSCIENCE_AUTOCAST_POINTWISE_BINARY_OPERATOR(chebyshev_polynomial_t, x, n)
TORCHSCIENCE_AUTOCAST_POINTWISE_TERNARY_OPERATOR(incomplete_beta, x, a, b)
TORCHSCIENCE_AUTOCAST_POINTWISE_QUATERNARY_OPERATOR(hypergeometric_2_f_1, a, b, c, z)
TORCHSCIENCE_AUTOCAST_POINTWISE_BINARY_OPERATOR(polygamma, n, z)
TORCHSCIENCE_AUTOCAST_POINTWISE_BINARY_OPERATOR(log_beta, a, b)
TORCHSCIENCE_AUTOCAST_POINTWISE_UNARY_OPERATOR(log_gamma, z)
TORCHSCIENCE_AUTOCAST_POINTWISE_BINARY_OPERATOR(regularized_gamma_p, a, x)
TORCHSCIENCE_AUTOCAST_POINTWISE_BINARY_OPERATOR(regularized_gamma_q, a, x)
TORCHSCIENCE_AUTOCAST_POINTWISE_UNARY_OPERATOR(modified_bessel_i_0, z)
TORCHSCIENCE_AUTOCAST_POINTWISE_UNARY_OPERATOR(modified_bessel_i_1, z)
