import pytest
import torch
import torch.testing

import torchscience.noise
from torchscience.testing import (
    ColoredNoiseScientificMixin,
    CreationOpDescriptor,
    CreationOpTestCase,
    CreationOpToleranceConfig,
)


def reference_violet_noise(size: int, *, dtype=torch.float64, generator=None) -> torch.Tensor:
    """Reference pipeline for stochastic comparison.

    Violet (purple) noise has PSD ~ f^2. It is the spectral mirror of brown
    noise: heavy high-frequency emphasis. Equivalently, violet noise is the
    discrete-time derivative of white noise. Generated by amplitude-shaping
    Gaussian white noise so that the DFT magnitude scales as f. The DC bin is
    naturally zero because the filter f vanishes at f=0; the output is
    therefore zero-mean by construction.
    """
    if generator is None:
        g = torch.Generator(device="cpu")
        g.manual_seed(12345)
    else:
        g = generator

    white = torch.randn(size, dtype=torch.float64, generator=g)
    spec = torch.fft.rfft(white)
    freqs = torch.fft.rfftfreq(size, d=1.0, dtype=torch.float64, device=white.device)
    filter_amp = freqs.abs()
    filtered = spec * filter_amp
    out = torch.fft.irfft(filtered, n=size)
    out = out / out.abs().max().clamp_min(1e-12)
    return out.to(dtype)


class TestVioletNoise(CreationOpTestCase, ColoredNoiseScientificMixin):
    # Violet noise: PSD ~ f^2, so alpha = +2.
    alpha = 2.0
    noise_func = staticmethod(torchscience.noise.violet_noise)

    @property
    def descriptor(self) -> CreationOpDescriptor:
        return CreationOpDescriptor(
            name="violet_noise",
            func=torchscience.noise.violet_noise,
            supported_dtypes=[
                torch.float16,
                torch.bfloat16,
                torch.float32,
                torch.float64,
            ],
            tolerances=CreationOpToleranceConfig(
                float32_rtol=1e-4,
                float32_atol=1e-4,
                float64_rtol=1e-5,
                float64_atol=1e-5,
            ),
            skip_tests={
                "test_reference_implementation",
                "test_torch_compile",
                "test_cuda_device",
                "test_dtype_device_combinations",
            },
            supports_meta=True,
            reference_func=None,
        )

    def test_matches_reference_with_generator(self):
        size = 64
        gen = torch.Generator(device="cpu").manual_seed(12345)
        result = torchscience.noise.violet_noise(size, dtype=torch.float64, generator=gen)
        gen2 = torch.Generator(device="cpu").manual_seed(12345)
        expected = reference_violet_noise(size, dtype=torch.float64, generator=gen2)
        torch.testing.assert_close(result, expected, rtol=1e-5, atol=1e-5)

    def test_reproducibility(self):
        a = torchscience.noise.violet_noise(
            100, generator=torch.Generator(device="cpu").manual_seed(0)
        )
        b = torchscience.noise.violet_noise(
            100, generator=torch.Generator(device="cpu").manual_seed(0)
        )
        torch.testing.assert_close(a, b)

    def test_different_generators_differ(self):
        a = torchscience.noise.violet_noise(200, generator=torch.Generator(device="cpu").manual_seed(1))
        b = torchscience.noise.violet_noise(200, generator=torch.Generator(device="cpu").manual_seed(2))
        assert not torch.allclose(a, b)

    def test_out_not_supported(self):
        buf = torch.empty(5)
        with pytest.raises(NotImplementedError):
            torchscience.noise.violet_noise(5, out=buf)

    def test_non_contiguous_memory_format_rejected(self):
        with pytest.raises(ValueError, match="contiguous"):
            torchscience.noise.violet_noise(5, memory_format=torch.channels_last)
