import math

import pytest
import torch
import torch.testing

import torchscience.noise
from torchscience.testing import (
    CreationOpDescriptor,
    CreationOpTestCase,
    CreationOpToleranceConfig,
)


def reference_pink_noise(size: int, *, dtype=torch.float64, generator=None) -> torch.Tensor:
    """Reference pipeline (float64 FFT) for stochastic comparison with a fixed generator.

    Pink noise is generated by amplitude-shaping Gaussian white noise so that the
    DFT magnitude scales as 1/sqrt(f). The DC bin (f=0) is set to zero because
    1/f is undefined there; this also guarantees the output is zero-mean.
    """
    if generator is None:
        g = torch.Generator(device="cpu")
        g.manual_seed(12345)
    else:
        g = generator

    white = torch.randn(size, dtype=torch.float64, generator=g)
    spec = torch.fft.rfft(white)
    freqs = torch.fft.rfftfreq(size, d=1.0, dtype=torch.float64, device=white.device)
    scales = torch.maximum(freqs.abs().sqrt(), torch.tensor(1e-6, dtype=torch.float64))
    filtered = spec / scales
    filtered[0] = 0.0  # 1/f at DC is undefined; zeroing makes the output zero-mean
    pink = torch.fft.irfft(filtered, n=size)
    mx = pink.abs().max().clamp_min(1e-12)
    pink = pink / mx
    return pink.to(dtype)


def _averaged_periodogram(size: int, num_seeds: int, base_seed: int = 0) -> tuple[torch.Tensor, torch.Tensor]:
    """Generate ``num_seeds`` independent realizations and return (freqs, mean_periodogram).

    Averaging reduces the chi-square variance of each FFT bin by a factor of
    ``num_seeds``, giving stable per-bin power estimates suitable for testing
    spectral-shape properties without flakiness.
    """
    freqs = torch.fft.rfftfreq(size, d=1.0, dtype=torch.float64)
    psd_sum = torch.zeros_like(freqs)
    for offset in range(num_seeds):
        gen = torch.Generator(device="cpu").manual_seed(base_seed + offset)
        x = torchscience.noise.pink_noise(size, dtype=torch.float64, generator=gen)
        spec = torch.fft.rfft(x)
        psd_sum += spec.abs() ** 2
    return freqs, psd_sum / num_seeds


class TestPinkNoise(CreationOpTestCase):
    @property
    def descriptor(self) -> CreationOpDescriptor:
        return CreationOpDescriptor(
            name="pink_noise",
            func=torchscience.noise.pink_noise,
            supported_dtypes=[
                torch.float16,
                torch.bfloat16,
                torch.float32,
                torch.float64,
            ],
            tolerances=CreationOpToleranceConfig(
                float32_rtol=1e-4,
                float32_atol=1e-4,
                float64_rtol=1e-5,
                float64_atol=1e-5,
            ),
            skip_tests={
                # Stochastic: compared under fixed generator in custom tests below.
                "test_reference_implementation",
                "test_torch_compile",
                # Only CPU and meta kernels exist; anchor-based dispatch errors on CUDA/MPS.
                "test_cuda_device",
                "test_dtype_device_combinations",
            },
            supports_meta=True,
            reference_func=None,
        )

    def test_matches_reference_with_generator(self):
        """Same CPU generator state should match the reference FFT pipeline."""
        size = 64
        gen = torch.Generator(device="cpu").manual_seed(12345)
        result = torchscience.noise.pink_noise(size, dtype=torch.float64, generator=gen)
        gen2 = torch.Generator(device="cpu").manual_seed(12345)
        expected = reference_pink_noise(size, dtype=torch.float64, generator=gen2)
        torch.testing.assert_close(result, expected, rtol=1e-5, atol=1e-5)

    def test_reproducibility(self):
        a = torchscience.noise.pink_noise(
            100, generator=torch.Generator(device="cpu").manual_seed(0)
        )
        b = torchscience.noise.pink_noise(
            100, generator=torch.Generator(device="cpu").manual_seed(0)
        )
        torch.testing.assert_close(a, b)

    def test_different_generators_differ(self):
        a = torchscience.noise.pink_noise(200, generator=torch.Generator(device="cpu").manual_seed(1))
        b = torchscience.noise.pink_noise(200, generator=torch.Generator(device="cpu").manual_seed(2))
        assert not torch.allclose(a, b)

    def test_out_not_supported(self):
        buf = torch.empty(5)
        with pytest.raises(NotImplementedError):
            torchscience.noise.pink_noise(5, out=buf)

    def test_non_contiguous_memory_format_rejected(self):
        with pytest.raises(ValueError, match="contiguous"):
            torchscience.noise.pink_noise(5, memory_format=torch.channels_last)

    # =========================================================================
    # Scientific properties of pink noise.
    #
    # Pink noise is defined by a power spectral density (PSD) inversely
    # proportional to frequency:
    #
    #     S(f) = C / f                                                    (1)
    #
    # Each test below asserts an independent, directly-derivable consequence
    # of (1). Together they pin down the spectral shape, the equal-energy-
    # per-octave property, the integral structure, and the zero-mean /
    # amplitude contracts of the implementation.
    # =========================================================================

    def test_log_log_psd_slope_is_approximately_minus_one(self):
        """Taking log of S(f) = C/f gives log S = -log f + log C, so a linear
        regression of log|X(f)|^2 against log f must have slope -1.

        We average the periodogram over 16 seeds (size=8192) to suppress the
        chi-square variance of individual FFT bins. Empirically the slope of
        the averaged spectrum is distributed as N(-1.00, 0.005) across seeds;
        the +/- 0.05 tolerance below is therefore ~10 standard deviations.
        """
        size = 8192
        freqs, psd = _averaged_periodogram(size, num_seeds=16)

        # Restrict to the band [4/N, 0.4]: avoid the lowest few bins (where
        # discretization dominates) and the Nyquist edge.
        mask = (freqs >= 4.0 / size) & (freqs <= 0.4)
        log_f = freqs[mask].log()
        log_p = psd[mask].clamp_min(1e-30).log()

        slope = (
            ((log_f - log_f.mean()) * (log_p - log_p.mean())).mean()
            / ((log_f - log_f.mean()) ** 2).mean()
        )

        assert abs(slope.item() - (-1.0)) < 0.05, (
            f"log-log PSD slope {slope.item():.4f} is not consistent with 1/f "
            f"(expected -1.0 +/- 0.05)"
        )

    def test_equal_power_per_octave(self):
        """For S(f) = C/f, the integral over an octave [f0, 2*f0] is

            integral_{f0}^{2 f0} C/f df = C * ln 2,

        which is independent of f0. Therefore every octave band contains
        approximately the same total power. This is the defining auditory
        property of pink noise ("equal energy per octave").

        We average 16 seeds at size=8192 and compare each octave's total
        power. Empirically the max/min ratio across high-resolution octaves
        (>=32 bins per octave) stays under 1.25; the threshold of 1.5 below
        is comfortably safe.
        """
        size = 8192
        freqs, psd = _averaged_periodogram(size, num_seeds=16)

        # Build octave bands [f0, 2*f0). Keep only those with >=32 bins so
        # the bin-count chi-square variance is small.
        powers = []
        cur_lo = 4.0 / size
        while cur_lo * 2.0 <= 0.5:
            cur_hi = cur_lo * 2.0
            in_band = (freqs >= cur_lo) & (freqs < cur_hi)
            if int(in_band.sum().item()) >= 32:
                powers.append(psd[in_band].sum().item())
            cur_lo = cur_hi

        assert len(powers) >= 5, (
            f"Need at least 5 high-resolution octaves for a meaningful test; "
            f"got {len(powers)}."
        )
        ratio = max(powers) / min(powers)
        assert ratio < 1.5, (
            f"Octave-band powers vary by factor {ratio:.3f} (expected ~1.0 "
            f"for equal-energy-per-octave). Per-octave powers: {powers}"
        )

    def test_integral_ratio_matches_log_ratio(self):
        """A stronger, basis-free form of the 1/f property: for any two bands
        [a, b] and [c, d],

            integral_a^b C/f df / integral_c^d C/f df = ln(b/a) / ln(d/c).

        Each band pair below is non-octave-aligned, so this is an independent
        check from `test_equal_power_per_octave`. Empirically the realized
        ratios deviate from the expected log-ratio by at most ~3% across 200
        seeds (M=16); the 10% tolerance is ~6 standard deviations.
        """
        size = 8192
        freqs, psd = _averaged_periodogram(size, num_seeds=16)

        band_pairs = [
            ((0.01, 0.05), (0.05, 0.25)),   # log-ratio = ln(5)/ln(5) = 1.0000
            ((0.005, 0.05), (0.05, 0.5)),   # log-ratio = ln(10)/ln(10) = 1.0000
            ((0.01, 0.10), (0.05, 0.25)),   # log-ratio = ln(10)/ln(5) ~ 1.4307
        ]
        for (a, b), (c, d) in band_pairs:
            expected = math.log(b / a) / math.log(d / c)
            p1 = psd[(freqs >= a) & (freqs < b)].sum().item()
            p2 = psd[(freqs >= c) & (freqs < d)].sum().item()
            ratio = p1 / p2
            rel_err = abs(ratio - expected) / expected
            assert rel_err < 0.10, (
                f"Band power ratio P([{a},{b}))/P([{c},{d}))={ratio:.4f} "
                f"deviates by {rel_err:.2%} from the 1/f prediction "
                f"ln(b/a)/ln(d/c)={expected:.4f}"
            )

    def test_mean_is_approximately_zero(self):
        """S(f) = C/f at f=0 is undefined; the standard treatment is to set
        the DC bin to zero, and a zero DC component implies a zero-mean time
        series:

            mean(x) = (1/N) * sum_n x_n = X[0] / N = 0.

        After max-abs normalization this property is preserved exactly (up to
        FFT round-off), so any non-trivial mean indicates the implementation
        is leaking energy into the DC bin. The 1e-6 threshold is many orders
        of magnitude above float64 round-off but well below any meaningful
        DC leakage.
        """
        size = 8192
        gen = torch.Generator(device="cpu").manual_seed(0x00b1)
        noise = torchscience.noise.pink_noise(size, dtype=torch.float64, generator=gen)
        m = noise.mean().abs().item()
        assert m < 1e-6, (
            f"mean(pink_noise) = {noise.mean().item():.6e}; expected ~0 from "
            f"a zeroed DC bin. (A nonzero mean indicates the DC component is "
            f"being amplified by the 1/sqrt(f) filter.)"
        )

    def test_output_normalized_to_unit_max_abs(self):
        """The implementation contract is that the returned signal is scaled
        so its peak absolute value is exactly 1. This is required for the
        slope / octave / integral-ratio tests above to be normalization-
        independent: scaling x -> alpha*x scales the PSD by alpha^2, which
        cancels in every ratio used.
        """
        for size in (16, 256, 8192):
            gen = torch.Generator(device="cpu").manual_seed(0x00b1)
            noise = torchscience.noise.pink_noise(size, dtype=torch.float64, generator=gen)
            assert noise.abs().max().item() == pytest.approx(1.0, abs=1e-12), (
                f"max|pink_noise(size={size})| = {noise.abs().max().item()} "
                f"(expected exactly 1.0)"
            )