import pytest
import torch
import torch.testing

import torchscience.noise
from torchscience.testing import (
    ColoredNoiseScientificMixin,
    CreationOpDescriptor,
    CreationOpTestCase,
    CreationOpToleranceConfig,
)


def reference_white_noise(size: int, *, dtype=torch.float64, generator=None) -> torch.Tensor:
    """Reference pipeline for stochastic comparison.

    White noise has a flat power spectrum (PSD = const). It is generated by
    drawing N i.i.d. samples from N(0, 1) and then zeroing the DC bin so the
    output is exactly zero-mean (mirroring the convention used for pink/brown
    where DC must be handled). The signal is then normalized by max |x|.
    """
    if generator is None:
        g = torch.Generator(device="cpu")
        g.manual_seed(12345)
    else:
        g = generator

    white = torch.randn(size, dtype=torch.float64, generator=g)
    spec = torch.fft.rfft(white)
    spec[0] = 0.0  # zero DC -> exact zero-mean (consistent with the other colors)
    out = torch.fft.irfft(spec, n=size)
    out = out / out.abs().max().clamp_min(1e-12)
    return out.to(dtype)


class TestWhiteNoise(CreationOpTestCase, ColoredNoiseScientificMixin):
    # White noise: PSD = const, so alpha = 0.
    alpha = 0.0
    noise_func = staticmethod(torchscience.noise.white_noise)

    @property
    def descriptor(self) -> CreationOpDescriptor:
        return CreationOpDescriptor(
            name="white_noise",
            func=torchscience.noise.white_noise,
            supported_dtypes=[
                torch.float16,
                torch.bfloat16,
                torch.float32,
                torch.float64,
            ],
            tolerances=CreationOpToleranceConfig(
                float32_rtol=1e-4,
                float32_atol=1e-4,
                float64_rtol=1e-5,
                float64_atol=1e-5,
            ),
            skip_tests={
                "test_reference_implementation",
                "test_torch_compile",
                "test_cuda_device",
                "test_dtype_device_combinations",
            },
            supports_meta=True,
            reference_func=None,
        )

    def test_matches_reference_with_generator(self):
        """Same CPU generator state should match the reference FFT pipeline."""
        size = 64
        gen = torch.Generator(device="cpu").manual_seed(12345)
        result = torchscience.noise.white_noise(size, dtype=torch.float64, generator=gen)
        gen2 = torch.Generator(device="cpu").manual_seed(12345)
        expected = reference_white_noise(size, dtype=torch.float64, generator=gen2)
        torch.testing.assert_close(result, expected, rtol=1e-5, atol=1e-5)

    def test_reproducibility(self):
        a = torchscience.noise.white_noise(
            100, generator=torch.Generator(device="cpu").manual_seed(0)
        )
        b = torchscience.noise.white_noise(
            100, generator=torch.Generator(device="cpu").manual_seed(0)
        )
        torch.testing.assert_close(a, b)

    def test_different_generators_differ(self):
        a = torchscience.noise.white_noise(200, generator=torch.Generator(device="cpu").manual_seed(1))
        b = torchscience.noise.white_noise(200, generator=torch.Generator(device="cpu").manual_seed(2))
        assert not torch.allclose(a, b)

    def test_out_not_supported(self):
        buf = torch.empty(5)
        with pytest.raises(NotImplementedError):
            torchscience.noise.white_noise(5, out=buf)

    def test_non_contiguous_memory_format_rejected(self):
        with pytest.raises(ValueError, match="contiguous"):
            torchscience.noise.white_noise(5, memory_format=torch.channels_last)
