#pragma once

#include <torchscience/csrc/quantized/cpu/special_functions/airy_ai.h>
#include <torchscience/csrc/quantized/cpu/special_functions/airy_ai_derivative.h>
#include <torchscience/csrc/quantized/cpu/special_functions/airy_bi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/airy_bi_derivative.h>
#include <torchscience/csrc/quantized/cpu/special_functions/bessel_j.h>
#include <torchscience/csrc/quantized/cpu/special_functions/bessel_j_derivative.h>
#include <torchscience/csrc/quantized/cpu/special_functions/bessel_y.h>
#include <torchscience/csrc/quantized/cpu/special_functions/bessel_y_derivative.h>
#include <torchscience/csrc/quantized/cpu/special_functions/bernoulli_number_b.h>
#include <torchscience/csrc/quantized/cpu/special_functions/beta.h>
#include <torchscience/csrc/quantized/cpu/special_functions/binomial_coefficient.h>
#include <torchscience/csrc/quantized/cpu/special_functions/bulirsch_elliptic_integral_el1.h>
#include <torchscience/csrc/quantized/cpu/special_functions/chebyshev_polynomial_t.h>
#include <torchscience/csrc/quantized/cpu/special_functions/chebyshev_polynomial_u.h>
#include <torchscience/csrc/quantized/cpu/special_functions/chebyshev_polynomial_v.h>
#include <torchscience/csrc/quantized/cpu/special_functions/chebyshev_polynomial_w.h>
#include <torchscience/csrc/quantized/cpu/special_functions/shifted_chebyshev_polynomial_t.h>
#include <torchscience/csrc/quantized/cpu/special_functions/shifted_chebyshev_polynomial_u.h>
#include <torchscience/csrc/quantized/cpu/special_functions/shifted_chebyshev_polynomial_v.h>
#include <torchscience/csrc/quantized/cpu/special_functions/shifted_chebyshev_polynomial_w.h>
#include <torchscience/csrc/quantized/cpu/special_functions/hermite_polynomial_he.h>
#include <torchscience/csrc/quantized/cpu/special_functions/carlson_elliptic_integral_r_c.h>
#include <torchscience/csrc/quantized/cpu/special_functions/carlson_elliptic_integral_r_d.h>
#include <torchscience/csrc/quantized/cpu/special_functions/carlson_elliptic_integral_r_e.h>
#include <torchscience/csrc/quantized/cpu/special_functions/carlson_elliptic_integral_r_j.h>
#include <torchscience/csrc/quantized/cpu/special_functions/carlson_elliptic_integral_r_k.h>
#include <torchscience/csrc/quantized/cpu/special_functions/carlson_elliptic_integral_r_m.h>
#include <torchscience/csrc/quantized/cpu/special_functions/carlson_elliptic_r_c.h>
#include <torchscience/csrc/quantized/cpu/special_functions/complete_carlson_elliptic_r_f.h>
#include <torchscience/csrc/quantized/cpu/special_functions/complete_carlson_elliptic_r_g.h>
#include <torchscience/csrc/quantized/cpu/special_functions/complete_elliptic_integral_e.h>
#include <torchscience/csrc/quantized/cpu/special_functions/complete_elliptic_integral_k.h>
#include <torchscience/csrc/quantized/cpu/special_functions/complete_elliptic_integral_pi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/complete_legendre_elliptic_integral_d.h>
#include <torchscience/csrc/quantized/cpu/special_functions/confluent_hypergeometric_0_f_1.h>
#include <torchscience/csrc/quantized/cpu/special_functions/cos_pi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/cosine_integral_ci.h>
#include <torchscience/csrc/quantized/cpu/special_functions/cosine_integral_cin.h>
#include <torchscience/csrc/quantized/cpu/special_functions/digamma.h>
#include <torchscience/csrc/quantized/cpu/special_functions/double_factorial.h>
#include <torchscience/csrc/quantized/cpu/special_functions/erf.h>
#include <torchscience/csrc/quantized/cpu/special_functions/erfc.h>
#include <torchscience/csrc/quantized/cpu/special_functions/exponential_integral_e.h>
#include <torchscience/csrc/quantized/cpu/special_functions/exponential_integral_e_1.h>
#include <torchscience/csrc/quantized/cpu/special_functions/exponential_integral_ei.h>
#include <torchscience/csrc/quantized/cpu/special_functions/factorial.h>
#include <torchscience/csrc/quantized/cpu/special_functions/falling_factorial.h>
#include <torchscience/csrc/quantized/cpu/special_functions/fibonacci_number_f.h>
#include <torchscience/csrc/quantized/cpu/special_functions/gamma.h>
#include <torchscience/csrc/quantized/cpu/special_functions/hankel_h_1.h>
#include <torchscience/csrc/quantized/cpu/special_functions/hankel_h_2.h>
#include <torchscience/csrc/quantized/cpu/special_functions/hyperbolic_cosine_integral_chi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/hyperbolic_sine_integral_shi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/incomplete_elliptic_integral_e.h>
#include <torchscience/csrc/quantized/cpu/special_functions/incomplete_elliptic_integral_f.h>
#include <torchscience/csrc/quantized/cpu/special_functions/incomplete_legendre_elliptic_integral_d.h>
#include <torchscience/csrc/quantized/cpu/special_functions/legendre_elliptic_integral_pi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/inverse_erf.h>
#include <torchscience/csrc/quantized/cpu/special_functions/inverse_erfc.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_amplitude_am.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_elliptic_cd.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_elliptic_cn.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_elliptic_dn.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_elliptic_sc.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_elliptic_sd.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_elliptic_sn.h>
#include <torchscience/csrc/quantized/cpu/special_functions/inverse_jacobi_elliptic_cd.h>
#include <torchscience/csrc/quantized/cpu/special_functions/inverse_jacobi_elliptic_cn.h>
#include <torchscience/csrc/quantized/cpu/special_functions/inverse_jacobi_elliptic_dn.h>
#include <torchscience/csrc/quantized/cpu/special_functions/inverse_jacobi_elliptic_sc.h>
#include <torchscience/csrc/quantized/cpu/special_functions/inverse_jacobi_elliptic_sd.h>
#include <torchscience/csrc/quantized/cpu/special_functions/inverse_jacobi_elliptic_sn.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_theta_1.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_theta_2.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_theta_3.h>
#include <torchscience/csrc/quantized/cpu/special_functions/jacobi_theta_4.h>
#include <torchscience/csrc/quantized/cpu/special_functions/log_beta.h>
#include <torchscience/csrc/quantized/cpu/special_functions/log_gamma.h>
#include <torchscience/csrc/quantized/cpu/special_functions/logarithmic_integral_li.h>
#include <torchscience/csrc/quantized/cpu/special_functions/modified_bessel_i.h>
#include <torchscience/csrc/quantized/cpu/special_functions/modified_bessel_i_derivative.h>
#include <torchscience/csrc/quantized/cpu/special_functions/modified_bessel_k.h>
#include <torchscience/csrc/quantized/cpu/special_functions/modified_bessel_k_derivative.h>
#include <torchscience/csrc/quantized/cpu/special_functions/neville_theta_c.h>
#include <torchscience/csrc/quantized/cpu/special_functions/neville_theta_d.h>
#include <torchscience/csrc/quantized/cpu/special_functions/neville_theta_n.h>
#include <torchscience/csrc/quantized/cpu/special_functions/neville_theta_s.h>
#include <torchscience/csrc/quantized/cpu/special_functions/prime_number_p.h>
#include <torchscience/csrc/quantized/cpu/special_functions/rising_factorial.h>
#include <torchscience/csrc/quantized/cpu/special_functions/sin_pi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/sinc_pi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/sine_integral_sin.h>
#include <torchscience/csrc/quantized/cpu/special_functions/sine_integral_si.h>
#include <torchscience/csrc/quantized/cpu/special_functions/sinhc_pi.h>
#include <torchscience/csrc/quantized/cpu/special_functions/spherical_bessel_j.h>
#include <torchscience/csrc/quantized/cpu/special_functions/spherical_bessel_y.h>
#include <torchscience/csrc/quantized/cpu/special_functions/spherical_hankel_h_1.h>
#include <torchscience/csrc/quantized/cpu/special_functions/spherical_hankel_h_2.h>
#include <torchscience/csrc/quantized/cpu/special_functions/spherical_modified_bessel_i.h>
#include <torchscience/csrc/quantized/cpu/special_functions/spherical_modified_bessel_k.h>
#include <torchscience/csrc/quantized/cpu/special_functions/tangent_number_t.h>
#include <torchscience/csrc/quantized/cpu/special_functions/trigamma.h>
