name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-cuda:
    name: Test CUDA - Python ${{ matrix.python-version }}
    runs-on: "torchscience-linux-cuda"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]
    steps:
      - run: "nvidia-smi"
      - uses: "actions/checkout@v4"
      - uses: "astral-sh/setup-uv@v6"
        with:
          python-version: ${{ matrix.python-version }}
      - run: "uv sync --locked --all-extras --dev"
      - run: "uv run pytest tests"
